# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
  };
  specs = rec {
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "b1b875982b17dabde9b4a37f3e229e74913e6db3";
      lastModified = 1789546076;
      narHash = "sha256-zVxLZiSnmaaPLwnhj7pwmqe3axBg/C6nG5JZsJMh2g4=";
    };
    unflake_git_https---codeberg-org-goldstein-unflake = {
      type = "git";
      url = "https://codeberg.org/goldstein/unflake";
      rev = "22d908471bf3201856cd10d22813d85c66a75907";
      lastModified = 1777745233;
      narHash = "sha256-5V1t58ijktiFDbsbpvgoX+SR7qqmlIA5IvvihxWWXMo=";
    };
  };
  deps = indirect_deps // builtins.mapAttrs (_: spec: builtins.fetchTree spec) specs;
  injections = rec {
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = {
    };
    unflake_git_https---codeberg-org-goldstein-unflake = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixos-unstable" "flake.nix" "";
    unflake_git_https---codeberg-org-goldstein-unflake = inject "unflake_git_https---codeberg-org-goldstein-unflake" "flake.nix" "";
  };
  inputs = {
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    unflake = universe.unflake_git_https---codeberg-org-goldstein-unflake;
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
